# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LZStudyingProj' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LZStudyingProj

  pod 'SnapKit', '~> 5.0.0'
  pod 'TABAnimated', '2.5.1'
  pod 'TMComponent', :git => 'https://github.com/RoyJoel/TMComponent.git', :tag => '0.8.7'
  pod 'SDWebImage', '~> 5.0'
  pod 'Alamofire'
  pod 'Toast-Swift'
  pod 'SwiftyJSON'
  pod 'SwiftFormat/CLI', '0.40.4'
  pod 'JXSegmentedView'
  pod 'Starscream'
  pod 'ReachabilitySwift'

  target 'LZStudyingProjTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'LZStudyingProjUITests' do
    # Pods for testing
  end

end
